### ISSUE TITLE
Identical badges with different file names = unnessesary downloads

### ISSUE THREAD

**Issue by WebMechanic** [csstools/cssdb#105]
Hi,
thanks for the site. It's a great ressource to check progress and innovations.

Each feature comes with a "stage" badge in .svg format. 
All filenames match the feature, but the actual file content is always the same.
- https://cssdb.org/images/badges/grid-layout.svg
- https://cssdb.org/images/badges/gap-properties.svg

identical content, and that's just for stage 3.

This results in several dozend downloads for no reason where a single badge for each stage level would do and could be cached.

Have a nice time.

**Comment by romainmenke** [comment]
Good point!

The reason they are different files is because they are also used externally.
This allows any plugin creator to grab their badge image and it will update if the stage progresses.

For example here : https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-color-hex-alpha#readme

<img width="481" alt="Screenshot 2022-03-17 at 08 14 36" src="https://user-images.githubusercontent.com/11521496/158756263-1755ba3f-c707-4082-8037-3382cc837139.png">

But the cssdb site is generated and all stages are known at the time of building.
So purely for cssdb we could indeed optimise this.

**Comment by Antonio-Laguna** [comment]
@WebMechanic we've reviewed this issue and after fixing it on #113 we've decided to revert the fix. 

The reason is that the CSSDB only has 128kb of images and all of them are lazy-loaded. Also, we'd love to keep these live-updated images so any plugin author can just toss this on their README and not worry about the stage the plugin is at anymore. This is true even for rejected (not shown anymore) specs such as color mod: https://cssdb.org/images/badges/color-mod-function.svg

The alternative for this would be to have some UI feature that enables you to generate such image link with a button but as things are it feels that it'd be more trouble than the bytes it would save.

We do appreciate the issue though and while it makes sense this is a tradeoff we're willing to make.

Thanks!

**Comment by WebMechanic** [comment]
Thanks for the feedback and looking into it! Muy apreciado.
I wasn't aware of the link between plugin and file name: 'twas just all the same file for me :D

Sure enough I know next to nothing about the inner workings of the site, just wondering if a bunch of redirect rules couldn't handle this -- but it's apparently more complicated than that.

Have a nice time!
